<?php
/**
 * See horde/config/prefs.php for documentation on the structure of this file.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE! DO NOT COPY prefs.php TO prefs.local.php!
 * Local overrides ONLY MUST be placed in var/config/trustr/prefs.local.php or
 * var/config/trustr/prefs.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/trustr/prefs-servername.php.
 */

